
name: 'Author Assign'

on:
  pull_request_target:
    types: [opened, reopened]

jobs:
  assign-author:
    runs-on: ubuntu-latest
    if: github.repository == 'reactplay/react-play'
    steps:
      - uses: toshimaru/auto-author-assign
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
